### ISSUE TITLE
Unittests for select_organization_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1004]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
pre_auth_view_models/select_organization_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1002

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/pre_auth_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by M-A-D-A-R-A** [comment]
Hey, can u assign it to me. thanks.

**Comment by M-A-D-A-R-A** [comment]
The test that are cases that are written already are for [pre_auth_screens](https://github.com/PalisadoesFoundation/talawa/tree/develop/test/widget_tests/pre_auth_screens). 
Is there any example for pre_auth_view_model? @sumitra19jha

**Comment by palisadoes** [comment]
Unassigning. It's been over a month.

**Comment by RandyKdev** [comment]
Good day @palisadoes, I would like to work on this. Please can you assign it to me?

**Comment by RandyKdev** [comment]
Good day @palisadoes, I have completed this issue, but with some minor changes.

The file `select_organization_view_model.dart` contains some functions, [showOrganizationList](https://github.com/PalisadoesFoundation/talawa/blob/30b28fe68f9088d34c441a2b62919c36b58db265/lib/view_model/pre_auth_view_models/select_organization_view_model.dart#L162) and [showSearchList](https://github.com/PalisadoesFoundation/talawa/blob/30b28fe68f9088d34c441a2b62919c36b58db265/lib/view_model/pre_auth_view_models/select_organization_view_model.dart#L263) whose sole purpose is to display views.

I think the file `select_organization_view_model.dart`, being a view model should not contain views. So I moved the two functions to the `views` folder.

I transferred both functions to the file `lib/views/pre_auth_screens/select_organization.dart` because that is the file handling the view for the select organization view model.

Is this ok?

**Comment by palisadoes** [comment]
That is a useful insight. Yes, refactor the code accordingly.

**Comment by RandyKdev** [comment]
Ok, opening a PR now.
