### ISSUE TITLE
Unittests for widget custom_avatar.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1127]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
custom_avatar.dart
```

This file can be found in the `lib/widgets` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1125

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/widgets)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by guptapriyanshu7** [comment]
@palisadoes , please assign this to me.

**Comment by palisadoes** [comment]
- [This test only shows 2% code coverage](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/widgets). We need 100%. 
- Reopening

**Comment by sudo-saksham** [comment]
Can I take up this issue? @palisadoes

**Comment by literalEval** [comment]
I would like to work on this issue if not already fixed.

**Comment by literalEval** [comment]
The existing test for this file looks complete to me, though Codecov shows only 81%.
@palisadoes can you please suggest which things can be added to the test ?

**Comment by palisadoes** [comment]
Unassigning due to lack of updates

**Comment by literalEval** [comment]
Sorry for unavailability. My laptop broke and had to buy a new one the last week.
Please reassign to me, I'll complete this issue. Thanks.

**Comment by literalEval** [comment]
Hello @palisadoes , using mockNetworkImage for the CachedNetworkImage always feeds it with an image and thus the errorWidget part of CachedNetworkImage can't be tested. That is what's lacking for now.

The options are:

1. Add mockNetworkImage to the test and keep it as is.
2. Add an additional nullable parameter to CustomAvatar (that will be cacheManager) and then use the cacheManager to manage what goes into the CachedNetworkImage during testing.

Please suggest what will be better option so that I can proceed.

**Comment by palisadoes** [comment]
@noman2002 Any thoughts?

**Comment by noman2002** [comment]
@literalEval I guess following the first method with not get the code coverage to 100%. if it gets the coverage up to 100% then go for the 1st method. 
if not, then proceed with second option.

**Comment by literalEval** [comment]
@noman2002 yeah the first method will never trigger any errors and thus the errorWidget can't be tested. I was asking if keeping that much of testing works or not. Otherwise I'll modify the original CustomAvatar to accept additional parameter and move with that procedure.

**Comment by noman2002** [comment]
Just make sure the UI doesn't break by making these changes.

**Comment by literalEval** [comment]
@noman2002 so I implemented a MockCacheManager and can now test the error widget too. The only thing that remains is the imageBuilder. I don't know why but it doesn't show this widget, but placeholder shows up. What should I do in this case ? The options are:

1. Spend more time in this small widget and find out the issue and write test. I don't think this will be a good idea as we have already given a lot of time on it and the functional parts of this widget are being covered in the test anyway. 

But please let me know if you know how to fix this. I'll do it then. 

2. Modify the widget itself, so that it looks the same but some lines will be removed, tricking the test coverage to think that the coverage has increased. It won't increase the test in reality though. 

3. Since the main things are covered in the tests I've written, let them be and don't proceed further. 

Please tell me how to proceed further. Thanks.

**Comment by noman2002** [comment]
I think you should spend some more time and figure it out. 
@palisadoes What you say ?

**Comment by palisadoes** [comment]
Yes, and if not, unassign the original issue

**Comment by literalEval** [comment]
Sure. As I am working on another issue. If no one takes this even after I complete the issue I'm working on, I'll take this again and try to fix.

**Comment by palisadoes** [comment]
@literalEval it's now been a week with neither updates nor expensive for the delay. I'll unassign you from this.

**Comment by nidhin29** [comment]
Can I take this issue I have written the test if you assign I can give pull request

**Comment by nidhin29** [comment]
@noman2002  @Ayush0Chaudhary can I take this issue

**Comment by nidhin29** [comment]
I have written test for this

**Comment by nidhin29** [comment]
I have written test for this If you assign me this I can give pull request

**Comment by nidhin29** [comment]
@noman2002  Sir can I take this issue

**Comment by nidhin29** [comment]
No response

**Comment by nidhin29** [comment]
@noman2002  Sir,can I take this issue

**Comment by nidhin29** [comment]
@noman2002 I have written test for this if you assign I can give pull request

**Comment by noman2002** [comment]
@nidhin29 Have some patience. It will get assigned to you once any maintainer will see it.

**Comment by nidhin29** [comment]
@noman2002 Sorry Sir

**Comment by noman2002** [comment]
Its fine but make sure not to repeat this.

**Comment by nidhin29** [comment]
@noman2002 Ok Sir, I'll never repeat this
