### ISSUE TITLE
Unittests for widget post_widget.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1139]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
post_widget.dart
```

This file can be found in the `lib/widgets` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1125

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/widgets)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by Tusharkhati** [comment]
Hello. I'm interested in contributing to this community. I'm a beginner at dart language since I have already made some Android/ iOS applications in flutter using dart language. I know how we can use APIs since I have made my mini project on it.
I'm a quick learner and It will be really helpful to me if you can guide me on this, I've already cloned the project on my machine but I'm a little confused there are so many different files.

can you also assign this work to me?
Thanks.

**Comment by palisadoes** [comment]
Unassigning, it's been over a month

**Comment by RandyKdev** [comment]
Hello @palisadoes, I would like to give this a shot.

**Comment by palisadoes** [comment]
Reopening as the coverage is only 78%

**Comment by ilakshaygupt** [comment]
Can you please assign me this issue ?

**Comment by Cioppolo14** [comment]
@ilakshaygupt I have now assigned you two issues. Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by AVtheking** [comment]
please assign me this issue

**Comment by Tilakraj-B** [comment]
can I work on this issue ?
