### ISSUE TITLE
App Stuck at loading , if the url is invalid

### ISSUE THREAD

**Issue by Tanmoy741127** [PalisadoesFoundation/talawa#1370]
**Describe the bug**
Currently after providing , the organisation url , it got stuck at that screen if server is not running.
What I assuming, it just checking the format of url [https://example.com]. 
The app should be responsible to show error and cause to user, and go one step back to refactor the issue.

**To Reproduce**

1. Open app
2. Provide any url [Valid format]
3. App will got stuck at `Select Organization Section`

**Expected behavior**
The app should be responsible to show error and cause to user, and go one step back to refactor the issue.

**Additional details**
- It's better to keep an endpoint in `talawa-api` to check, whether it's an talawa service or not. 
- Also the organization url need to be in this format http://<url>/graphql
- The app should be compaitable , if the user provide http://<url> . It should retry the /graphql in case user has not provided

**Comment by palisadoes** [comment]
This issue is being reopened as the reporter bug is still present. The Pull Request was closed by the submitter without him providing a rationale.

**Comment by SiddheshKukade** [comment]
Actually here the steps are in a wrong order & that might be a reason due to which application is behaving in a unexpected way. 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Open app
> 
>     2. Provide any url [Valid format]
> 
>     3. App will got stuck at `Select Organization Section`
> 

Correct Steps  :
1. Start App
2. In the Server URL Screen: 
   - Provide server URL (can be valid or invalid)
   - Click on verify button to check if it works.
   - If success message then click on login or signup
   - If wrong URL message is provided then we don't have to click on login or signup buttons
