### ISSUE TITLE
[Feature Request] Add posts from the Post page

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa#1566]
**Is your feature request related to a problem? Please describe.**
The feature to add posts from the Post page only, as discussed in the Talawa GSoc video.

**Describe the solution you'd like**
I propose implementing something like this
![IMG_20230225_195813.jpg](https://user-images.githubusercontent.com/95746190/221362327-558dca53-4d48-4271-a12e-c6645c833380.jpg)

After **write something** we can have the option to add posts and all other things can be implemented accordingly 
.

**Describe alternatives you've considered**
I am thinking of something like **The facebook example

Also we can show the post added by the user instantly rather than fetching it again.

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 @TheHazeEffect 
Can I work on this??

**Comment by noman2002** [comment]
@Ayush0Chaudhary And also remove the post Button from nav bar and implement the functionality in the form of Popup or bottomsheet.

**Comment by Ayush0Chaudhary** [comment]
Understood 🫡

**Comment by palisadoes** [comment]
1. I've been looking at my apps, and I didn't realize that  all use the `+` button because the apps can do other things than just posting.
1. I was mixing up WhatsApp with the others. Sorry.

They all have an animation drawer widget that comes up from the bottom to make people realize the connection between the two screens. I think ours just pops up so a simple animation would work.

This is not as broken as I thought. My mistake, but the afore mentioned animation would be useful.

**Comment by palisadoes** [comment]
Closing as this is not required
