### ISSUE TITLE
Modify authorised list and .gitignore accordingly

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa#1573]
Yes. The flutter file should be in `.gitignore` for now. It's more likely that many more people will reproduce this mistake than those who purposefully modify the file.

_Originally posted by @palisadoes in https://github.com/PalisadoesFoundation/talawa/issues/1563#issuecomment-1445281717_

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 this is small issue, please assign me this

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 @TheHazeEffect we cannot add firebase_options in our gitignore because **it is necessary** for the our app to run

without firebase_options, it will throw error in main.dart
  

![Screenshot from 2023-02-27 03-25-08](https://user-images.githubusercontent.com/95746190/221439788-6b71e687-c589-4d52-9921-168bffa408fd.png)

**Comment by palisadoes** [comment]
I thought the API used the Firebase configuration to do the interaction on behalf of the Talawa mobile app client.

This was because each talawa-api user will want to use their own Firebase account to communicate with their mobile apps.

Based on that the Firebase configuration related files should be ignored. If that is not case, the code needs a review.

@xoldyckk @SiddheshKukade please comment.

**Comment by palisadoes** [comment]
Isn't that file generated when the Firebase package is installed?

If that's the case, we should be able to ignore it in gitignore. Correct?

**Comment by palisadoes** [comment]
And if that's the case the fireplace reference in the code could be removed.

**Comment by Ayush0Chaudhary** [comment]
> Isn't that file generated when the Firebase package is installed?
> 
> If that's the case, we should be able to ignore it in gitignore. Correct?

yes the file is generated

**Comment by Ayush0Chaudhary** [comment]
> And if that's the case the fireplace reference in the code could be removed.

yes it can be done and the app will work fine but we have to step to add this function in main.dart in Installation.md
https://github.com/PalisadoesFoundation/talawa/blob/337f61e841b7b38ede08c5539c88f4f0487ecc92/lib/main.dart#L41-L48

**Comment by SiddheshKukade** [comment]
> I thought the API used the Firebase configuration to do the interaction on behalf of the Talawa mobile app client.
> 
> This was because each talawa-api user will want to use their own Firebase account to communicate with their mobile apps.
> 
> Based on that the Firebase configuration related files should be ignored. If that is not case, the code needs a review.
> 
> @xoldyckk @SiddheshKukade please comment.

@palisadoes Sir,  I don't think we should add the files from `android` / `ios` folder to the `.gitignore`. While developing cross platform apps with frameworks like React Native and Flutter. We sometimes have to perform custom configuration in these files.
For ex. This [article](https://www.digitalocean.com/community/tutorials/flutter-firebase-setup) on setting up firebase with flutter shows how we need to change the internal android files to do so. Also the official ` .gitignore ` from  flutter [here](https://github.com/flutter/flutter/blob/master/.gitignore) doesn't  have that.

About the `firebase_options.dart` file: I can see that the firebase is now handled on the backend from [here](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.env.sample). I think we can refactor the firebase setup on the app to make sure that It work with backend. I can do this you can assign me this.

**Comment by palisadoes** [comment]
@SiddheshKukade It may not be that simple, new developers will always be adding configuring Firebase to add the parameters to the API. This means that this specific file will always be generated and be a distraction. I understand that those directories should always be included but this file may need to be an exception. Is this a manageable risk to take or could there be another solution?

**Comment by SiddheshKukade** [comment]
@palisadoes  Sir, I think you're right.  @Ayush0Chaudhary could you please elaborate specifically which files are getting auto generated that you've mentioned about in https://github.com/PalisadoesFoundation/talawa/issues/1573#issuecomment-1445976815  ?

**Comment by Ayush0Chaudhary** [comment]
> @palisadoes  Sir, I think you're right.  @Ayush0Chaudhary could you please elaborate specifically which files are getting auto generated that you've mentioned about in https://github.com/PalisadoesFoundation/talawa/issues/1573#issuecomment-1445976815  ? 

Only firebase_options.dart

**Comment by Ayush0Chaudhary** [comment]
@SiddheshKukade can we do firebase_cli setup

And add below snippet in main.dart

  `await Firebase.initializeApp( 
     options: DefaultFirebaseOptions.currentPlatform, 
   );`

**Comment by Ayush0Chaudhary** [comment]
And let it give the error that firebase_option is missing

The user will add the file later

**Comment by Ayush0Chaudhary** [comment]
And let it give the error that firebase_option is missing

The user will add the file later

**Comment by SiddheshKukade** [comment]
> Only firebase_options.dart

If you are asking about this file  https://github.com/PalisadoesFoundation/talawa/blob/develop/lib/firebase_options.dart
then this file is required to make the firebase work properly in mobile app because it takes the key from the local cache and initializes them with a firebase object which can be used anywhere in the application if required, for firebase related use-cases.


> And let it give the error that firebase_option is missing
> 
> The user will add the file later @SiddheshKukade

I  am also not facing any error or issues with the firebase function as you can see from the below screenshot. The app is running fine.

![image](https://user-images.githubusercontent.com/65951872/221656065-dade22bc-adff-4e78-8174-a0d129998c24.png)

**Comment by palisadoes** [comment]
Are you saying that we need to include the reference to the firebase package in main.dart to generate the keys?

**Comment by SiddheshKukade** [comment]
> Are you saying that we need to include the reference to the firebase package in main.dart to generate the keys?

No, actually the reference is already there in the `main.dart` file. the `firebase_options.dart` just takes the data that is retrieved when the user log in every time and initializes that in the local firebase library according to the platform i.e `iOS` or `Android`.

**Comment by palisadoes** [comment]
Why is this necessary if the Firebase interaction is between the Firebase API and Talawa API?

It would seem to be that there would be no need for importing Firebase librayry into the mobile app.

**Comment by SiddheshKukade** [comment]
It is acting as a helper function to ensure the correct setup according to the platform whicjh can be iOS or android

**Comment by palisadoes** [comment]
Can this be done some other way without using a package that will generate an independent set of files for each developer?

**Comment by SiddheshKukade** [comment]
Hello @palisadoes Sir , I've checked about the extra files getting generated due to firebase today & I've found out that 
these are the files that are getting generated
![image](https://user-images.githubusercontent.com/65951872/222962975-c6ebec01-ab80-45a4-961a-73caac50c4f3.png)


These files are getting generated due to a test file from here: 

![image](https://user-images.githubusercontent.com/65951872/222963073-792e2652-8856-4d87-868d-747cc7253601.png)


So we don't need to merge them into our project for development.
adding these to `.gitignore` can fix this issue. 

Please assign me (@SiddheshKukade ) so that I can make a pull request.
Thanks.

**Comment by palisadoes** [comment]
@Ayush0Chaudhary For the sake of expediency I'll assign this to @SiddheshKukade
