### ISSUE TITLE
[Enhancement] Overflow Snackbar in Switch organization

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa#175]
### Description
The issue is observed in log while opening the Profile Page. The fact this issue occurs is because the user is not part of any organization at all. When user navigate to the profile screen, a query is being made using the organization_id whose value is null at the time of call leading to this issue.

**Observed Behaviour**
![WhatsApp Image 2021-03-14 at 8 13 17 AM](https://user-images.githubusercontent.com/35868598/111055579-40649e80-849d-11eb-896b-b4f2c7ccddbb.jpeg)

**Expected Behaviour**
No save button or correct snackbar widget should appear

I am working on this.

**Comment by Sagar2366** [comment]
@sumitra19jha please follow guidelines while creating issues and pr's. Add more details to this issue - observed behavior, expected behaviour, environment details, fix suggestion, snapshots(you have already it)/video.
With the proper description of the issue, if not you, others can clearly understand the requirement and work on it.

**Comment by sumitra19jha** [comment]
ok @Sagar2366 
Changing the issue description

**Comment by sumitra19jha** [comment]
@Sagar2366 I made a new PR request based on your feedback
#315 PR created

**Comment by Sagar2366** [comment]
@sumitra19jha , this is not helping to address the problem we are trying to solve. 
Please discuss the issues in slack channels, if you have any doubts before implementing solution.

**Comment by sumitra19jha** [comment]
Ok
