### ISSUE TITLE
Bug Report: Bumps firebase_messaging from 14.6.1 to 14.6.2.

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1879]
**Describe the bug**
Update [firebase_messaging](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging) from 14.6.1 to 14.6.2. See PR #1874.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AbhinavISM** [comment]
Hi sir/mam, I can easily tackle this issue, please assign this task to me. I have already setup the project, just waiting to be assigned as per the contribution guidelines

**Comment by AbhinavISM** [comment]
Hi, which flutter version do I have to run this app on?
I am getting the following error on running in physical android device :

Because talawa depends on flutter_localizations from sdk which depends on intl 0.18.0, intl 0.18.0 is required.
So, because talawa depends on intl ^0.17.0, version solving failed.

I am running flutter 3.10.0
seems like this sdk depends on different version of flutter_localizations package.
please let me know what flutter version do we have to compile on

**Comment by palisadoes** [comment]
Our tests are run against version 3.7.3

**Comment by AbhinavISM** [comment]
Hi, the firebase_messaging package is already using version^14.6.3 as of now. Do you want me to downgrade it? Otherwise please close the issue.
