### ISSUE TITLE
Bug Report: Update shared_preferences from 2.1.1 to 2.1.2

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1893]
**Describe the bug**
Update [shared_preferences](https://github.com/flutter/packages/tree/main/packages/shared_preferences) from 2.1.1 to 2.1.2.  See PR #1889. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AbhinavISM** [comment]
Hello sir/mam,
please assign me this issue I'm willing to contribute.

**Comment by AbhinavISM** [comment]
Hi, which flutter version do I have to run this app on?
I am getting the following error on running in physical android device :

Because talawa depends on flutter_localizations from sdk which depends on intl 0.18.0, intl 0.18.0 is required.
So, because talawa depends on intl ^0.17.0, version solving failed.

I am running flutter 3.10.0
seems like this sdk depends on different version of flutter_localizations package.
please let me know what flutter version do we have to compile on

**Comment by palisadoes** [comment]
Our tests run on `v3.7.3`
