### ISSUE TITLE
Write tests for map_screen.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2146]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/views/after_auth_screens/venue/map_screen.dart

```

The current code coverage for this file can be found here:
-  https://app.codecov.io/gh/PalisadoesFoundation/talawa?displayType=list

**Comment by imshivam-gupta** [comment]
@palisadoes I would like to work on this issue.. can you please assign it to me?

**Comment by noman2002** [comment]
@imshivam-gupta You have commented on so many issues. Make sure not to repeat this behavior.

**Comment by Manik2708** [comment]
@noman2002 @palisadoes Can you assign this issue to me?

**Comment by noman2002** [comment]
@Ayush0Chaudhary Please answer his queries.

**Comment by Manik2708** [comment]
> While writing tests for this problem, I encountered a problem, I want to see Maps on the screen and for that an API key is required which I have arranged but I want to know how Talawa handles secret APIs or secret properties? As the official [docs](https://developers.google.com/maps/flutter-package/config) says to enter the API Key in `build.gradle` file also. So I want to ask How does Talawa achieve this?

@Ayush0Chaudhary Also please see that in `test/views/after_auth_screens/events/event_info_body_test.dart`, no widget of type `MapScreen` is expected. In other tests of MapScreen like `test/widget_tests/after_auth_screens/events/event_info_page_test.dart` and `test/widget_tests/after_auth_screens/events/create_event_page_test.dart`, a similar type of structure is seen. So I want to know whether the feature of Google Maps is implemented or not, or should I firstly work on it's implementation. Then these of the following issues needs to be addressed first:
1) Installing API Key safely in `build.gradle` file.
2) Updating the `Installation.md` file for giving future developers a source for free API Keys to test because the API Keys of Google Maps are paid. I have found a source but Maintainers need to verify it.
I request @noman2002 @palisadoes to look into this issue.

**Comment by Manik2708** [comment]
After consulting to @Dante291, I got to know that Google Maps Feature is going to be removed from Talawa before this year ends. @noman2002 Please tell if I should work further on this issue.

**Comment by Dante291** [comment]
@noman2002 Currently Google Maps feature is only used in Event info and for the release of the MVP @palisadoes has created this [issue](https://github.com/PalisadoesFoundation/talawa/issues/2193) for the removal of maps functionality. So please confirm if that's the case.

**Comment by Manik2708** [comment]
Should I unassign myself @noman2002? As I don't think spending more time on this issue is worth. Also I request you to link this issue to #2193 so that when Maps feature is removed completely, this issue also gets closed automatically.
