### ISSUE TITLE
Adding a comment to a news feed entry fails

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2190]
**Describe the bug**
- Please work with @Ayush0Chaudhary for comments, advice and review of your PR.

**To Reproduce**

- https://youtu.be/86AzK_Y_GCQ?t=48

**Expected behavior**
- Comment created 

**Actual behavior**
- No comment created

**Screenshots**
- N/A

**Additional details**
- You must get the test **_code coverage up to 100%_** for any edited files. No functionality must be removed to achieve this goal.

**Comment by imshivam-gupta** [comment]
@palisadoes I would like to work on this issue.. can you please assign it to me?

**Comment by Ayush0Chaudhary** [comment]
Please solve other issues first.

**Comment by imshivam-gupta** [comment]
@Ayush0Chaudhary Currently I have no issue assigned. I would like to work upon this issue.. Can you please assign it to me?

**Comment by imshivam-gupta** [comment]
@palisadoes @noman2002, I've ensured that comments are being successfully added to the database. However, they aren't currently visible because the GraphQL client is using the query commentsByPost(id:$id), which is not present in the talwa-api.

At this point, I have a couple of proposed solutions. Firstly, I can update the code to ensure that comments are added to the database. Then, when the talwa-api executes a GraphQL query, the comments will become visible.

Alternatively, I can create an issue on talwa-api and address it myself. I've identified what needs to be added to talwa-api, and I can work on this issue sequentially to ensure a comprehensive resolution.

Please provide guidance on which approach to take.

![image](https://github.com/PalisadoesFoundation/talawa/assets/93479496/9f121a29-5835-47dc-b555-385e4d6265b8)

**Comment by imshivam-gupta** [comment]
@noman2002 @palisadoes Can you please confirm which way to proceed?

**Comment by noman2002** [comment]
@imshivam-gupta Create an issue on the api.

**Comment by imshivam-gupta** [comment]
I have already created a PR for this issue which is yet to be approved.
