### ISSUE TITLE
User can't Switch between Themes and language 

### ISSUE THREAD

**Issue by tarun824** [PalisadoesFoundation/talawa#2226]
**Is your feature request related to a problem? Please describe.**
     Yes,
     Once chosen initially, there is no option or space to change Language or Theme (Dark/White).

**Describe the solution you'd like**
I would like create functionality to switch between language and Themes and create a page for app settings and Make a space for Themes and Language .I will also like to add "Edit profile" and Log Out button in that page. There is some code written to switch between Themes that i will update. to my code.

**Additional context**

These are some designs i have came up with
a)

![Screenshot_1702041142](https://github.com/PalisadoesFoundation/talawa/assets/142694988/9bfff357-33fc-456c-9a08-331516ca845e)
b)

![Screenshot_1702041290](https://github.com/PalisadoesFoundation/talawa/assets/142694988/378e9ab8-9d11-4830-b754-361654918eca)
c)

![Screenshot_1702041526](https://github.com/PalisadoesFoundation/talawa/assets/142694988/e6405e20-339c-4457-80b8-a247f780c9cf)

If there is any other design let me know we can implement that 

and i would like recommend to go with c) because it will be user-friendly and even if extra settings added to the app it can grouped here.
@palisadoes @noman2002 @Ayush0Chaudhary

**Comment by palisadoes** [comment]
Though this would be a good feature, we are focusing on:

1. breaking bugs
1. existing features that don't work as expected
1. getting our testing coverage up to 95% 

When we complete these, then we can work on issues like this one. The features you are suggesting would be better placed on the profile page where all aspects of the individual user's experience could be edited in one place. We can continue discussing what that would look like, but a PR would not be acceptable because of the prioritization.

We need to get our code less buggy.

**Comment by tarun824** [comment]
Ok sir ,Assign this when you feel it is the right time. 
Till then, I will be focusing on these three things.
