### ISSUE TITLE
GitHub Action Required for Translation Files 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2242]
We need to create a GitHub action that during the PR process checks all the translation files to make sure that there are translations in all the non-default languages for each English default language entry.

As part of the PR for this issue, all the translations must be correctly present

- **NOTE:** Please watch this video on how to proceed.
[![Click me to start video](https://img.youtube.com/vi/GlqUm1UO-xM/0.jpg)](https://www.youtube.com/watch?v=GlqUm1UO-xM)

**Comment by Dante291** [comment]
@palisadoes I can work on this.

**Comment by ibishal** [comment]
can i try this?

**Comment by Dante291** [comment]
Also I just checked there are so many words that should be manually added into these translation files of different languages, because currently the text in talawaErrorDialogBox, Snackbar etc. show text in default language even though when different language is selected. 

This will require testing of correct translation of words through out the app, I'm planning to add this testing and adding of the words to ensure that translation works properly throughout the app in this issue only.

Or should I just focus on only this issue and later add these parts by making new issue?

**Comment by Dante291** [comment]
> @Dante291 Assigned to @ibishal as he is new here, let him work on this one. If he is not able to do it then I'll assign it to you. Also you can help him in the slack if anything.

Roger that sir.

**Comment by Dante291** [comment]
@ibishal are you still working on this?

**Comment by Dante291** [comment]
@noman2002 i could work on this now

**Comment by Cioppolo14** [comment]
@Dante291 Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by rahularora27** [comment]
Can I work on this?

**Comment by AVtheking** [comment]
Can I work on this ?

**Comment by AVtheking** [comment]
hi the video link you have provided has no video ,please provide correct link

**Comment by palisadoes** [comment]
1. Please resubmit an updated PR for this issue where you specify the directory to be checked using ArgParse. That way we can use it with other repos.
