### ISSUE TITLE
Explore Events page is failing to fetch Events.

### ISSUE THREAD

**Issue by Azad99-9** [PalisadoesFoundation/talawa#2307]
**Describe the bug**
**Explore Events page not working properly.**
The `Explore Events page` fails to retrieve events from the server, consistently displaying an `empty list message` on the screen despite the` existence of events` in the database.

**To Reproduce**

1. Navigate to Explore Events page.
2. Refresh the page / Create an event.

**Expected behavior**
The `created events` / `existing events from database` should be shown on screen in a vertical scrolling fashion.

**Actual behavior**
`empty list` message is being shown always, despite the events present in the database.

**Screenshots**
**Actual**
![Screenshot_20240106-041638](https://github.com/PalisadoesFoundation/talawa/assets/120930148/cbae99e2-06de-401f-96e5-1d98c914645f)

**Expected**
![Screenshot_20240106-041619](https://github.com/PalisadoesFoundation/talawa/assets/120930148/555a838c-c0ea-41a2-9518-33b8af78647b)

**Additional details**
1. The Details of the Event are also not properly being fetched into the `EventCard` and `Event Page`.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Azad99-9** [comment]
@noman2002 @Cioppolo14 @Kevoniat please assign me this issue, I would like to work on this.

**Comment by Dante291** [comment]
https://github.com/PalisadoesFoundation/talawa/issues/2195

This issue already exists and someone is working on it, the reason why events are not getting fetched because of some problem related to firebase. Right when app initialise if you check debug console you could see graphql exception related to this.

**Comment by Azad99-9** [comment]
@Dante291 This issue is different from the issue you have mentioned.
1. The issue you have mentioned solely  focuses on creating a new event.
2. This issue focuses on fetching the events existing in the database.

**Comment by Dante291** [comment]
@Azad99-9 This is the exception you get when you try to make a new event 

![image](https://github.com/PalisadoesFoundation/talawa/assets/103507835/d8c5b9dd-b8e7-4fb2-9690-b6aa97925f99)

and this is the exception when you fetch events 

![image](https://github.com/PalisadoesFoundation/talawa/assets/103507835/72612d25-4658-4cfc-818f-0688e6f8dee1)

which are basically same, this exception is occurring due to some error related to firebase. 

You could work on this though, this will resolve both issues ig.

**Comment by Dante291** [comment]
> @Dante291 Please understand This issue is different from the issue you have mentioned.
> 
> 1. The issue you have mentioned solely  focuses on Failure of creating a new event.
> 2. This issue focuses on failure of fetching the events existing in the database.
> 3. Try creating an Event through admin panel and then try to find it in explore events page. It's not possible to see the created event in the explore events page
>    But it's visible in admin panel.

Yeah event is getting created successfully but the main problem is with fetching ig so basically https://github.com/PalisadoesFoundation/talawa/issues/2195 this issue should be about fetching of events is giving exception due to firebase?? maybe this issue is occurring because we are using same query to fetch events just after making a new event.

**Comment by Azad99-9** [comment]
@Dante291 I am working with @Abhisheksainii on this.

**Comment by Dante291** [comment]
> @Dante291 I am working with @Abhisheksainii on this.

I figured out the root cause of the problem by some lil debugging 

![Screenshot 2024-01-06 130842](https://github.com/PalisadoesFoundation/talawa/assets/103507835/21d03654-33fc-4226-b9e7-b63178e31191)

![Screenshot 2024-01-06 130820](https://github.com/PalisadoesFoundation/talawa/assets/103507835/52c4a2ca-a791-4bb2-a930-9ae7d6c3e4da)


I think the problem is with fetchOrgEvents query (it is stated as mutation but I think that's an error and it should be query not mutation) which may be related to backend side ig.

**Comment by Abhisheksainii** [comment]
@Dante291 nice work bro. This will surely help the backend developer to resolve the issue

**Comment by Dante291** [comment]
> @Dante291 nice work bro. This will surely help the backend developer to resolve the issue

No ig the issue is  fetchOrgEvents with query only because in admin portal events are getting fetched successfully, so it might not be a problem related to backend but with the query only, you guys could further work on this to find the main cause and if its the query do update it and ig that will fix the problem.

**Comment by imshivam-gupta** [comment]
@Dante291 Yes you are right I solved an issue earlier in which comments were not visible, initially I thought it was backend issue but then I realized  I was able to fetch the comments by just modifying the query. Events can be fetched in a similar way.
