### ISSUE TITLE
The calendar in the events page is showing wrong selected duration

### ISSUE THREAD

**Issue by Hrishikesh-Bhagwat** [PalisadoesFoundation/talawa#631]
Issue Description:
The calendar in the events page is showing wrong selected duration. 1 week option shows 2 weeks time,
2 weeks option shows 1 month, and 1 month  shows 1 week time.
Screenshots:
![Screenshot_20210408-183246](https://user-images.githubusercontent.com/79875904/114036487-bcd07e80-989d-11eb-86f1-37099c5b729e.jpg)
![Screenshot_20210408-183314](https://user-images.githubusercontent.com/79875904/114036492-be9a4200-989d-11eb-8f82-b9d991c8373c.jpg)
![Screenshot_20210408-183308](https://user-images.githubusercontent.com/79875904/114036499-bfcb6f00-989d-11eb-8875-1fe15900eb58.jpg)
Would you like to work on this?
Yes :)

**Comment by arteevraina** [comment]
@Hrishikesh-Bhagwat Can you please elaborate this issue ?

**Comment by Hrishikesh-Bhagwat** [comment]
Hi Arteev I know my description is incomplete. The issue is genuine but this got posted incompletely by mistake. I am soon going to update it.

**Comment by Hrishikesh-Bhagwat** [comment]
@arteevraina it looks valid now? :)

**Comment by Hrishikesh-Bhagwat** [comment]
Actually my phone stopped working. I was typing from the phone as wifi was down for sometime and hotspot was slow.

**Comment by arteevraina** [comment]
No worries @Hrishikesh-Bhagwat! But that is actually not an issue. A few days back I also researched on this and came to know that package `table_calendar` https://pub.dev/packages/table_calendar is meant to work this way only. For example, if you click on 2 weeks then it will show you two weeks, if you click on a month, then it will show you a month. It is not like that if it is showing 2 weeks then the calendar should show 2 weeks. It is kind of confusing. That's why I thought to ask if you to update the issue initially. Are you able to get what I am trying to convey ? :)

**Comment by Hrishikesh-Bhagwat** [comment]
No I did not get you it sound like a=~a 😅

**Comment by arteevraina** [comment]
See, if you click on `2 weeks`, then only you will get 2 weeks actually in the calendar. Try to play with the calendar for some time you will get it. If still not, comment here, I will post a recording video.
