### ISSUE TITLE
After joining organization the profile page shows no organization joined 

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#674]
BUG 

How to occur it 

Just login and join any organization and go to the profile page. You will find this bug

Vedio 

https://user-images.githubusercontent.com/55004621/115119992-b4c4bd00-9fc8-11eb-842c-636cd5c1a1d9.mp4

Expected behavior the name of the current organization should be shown

**Comment by yasharth291** [comment]
@Sagar2366  I would like to work on it sir

**Comment by Hrishikesh-Bhagwat** [comment]
I think there is an issue about org not showing

**Comment by CyberWake** [comment]
PR #607 will fix this issue automatically

**Comment by yasharth291** [comment]
Is there any issue opened like this already if yes can you please mention it here @CyberWake

**Comment by CyberWake** [comment]
The issue number is #514 it is stat  to auto-update members page in any case of change in current orgID via profile page.
And this indirectly updates the profile page as well due to the option of switch orgID existing over it
As well as the issue was further appended to other screens to auto update on suggestion of @Sagar2366 sir

**Comment by yasharth291** [comment]
ok brother i am closing this issue as it is a duplicate one. Thanks @CyberWake

**Comment by CyberWake** [comment]
Sure bro 🙂
