### ISSUE TITLE
Pull Request Code Quality Automations

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#736]
We have spent some time refactoring the code base. Each pull request now automatically analyzes your code for undesirable characteristics.

1. The Dart Package Analyzer `dart-package-analyzer` ensures consistent formatting
1. We automatically evaluate each Dart file submitted to ensure they are all under 300 lines in length (To be enforced after May 22 2021)

Please ensure your submissions meet these guidelines. Our [CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa/blob/master/CONTRIBUTING.md) file explains what you'll need to do.

**Comment by sumitra19jha** [comment]
@palisadoes Can I work on this issue?

**Comment by sumitra19jha** [comment]
@palisadoes @Sagar2366  Can we update the contributing guideliness further.
Recently we have done a lot of changes and some are going on:

1. File Size limited to 300 lines
2. Linting should be followed
3. Separation of business logic form UI
4. Use SizeConfig file to scale the UI, rather than constant value

Some of them are missing in the documentation, and some needs to be elaborated more. Can I work on updating the documentation further?

**Comment by palisadoes** [comment]
@sumitra19jha go ahead

**Comment by sumitra19jha** [comment]
> @sumitra19jha go ahead

Ok

**Comment by palisadoes** [comment]
We have updated the deadline to May 22nd
