### ISSUE TITLE
Automatically Add Trailing Comma to Dart Files During Pull Requests. 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#753]
**Is your feature request related to a problem? Please describe.**
1. Issue #735 mentioned that we need to standardize on the code base formatting by consistently adding trailing commas to the code blocks.
2. Pull request #752 did this formatting manually. This is not a sustainable solution. 

**Describe the solution you'd like**
We need an way to automatically add these commas as part of the pull request GitHub actions process.

**Comment by nayakastha** [comment]
[https://github.com/dart-lang/linter/pull/2557](https://github.com/dart-lang/linter/pull/2557) -> this is a discussion that might help to come to a conclusion.

**Comment by palisadoes** [comment]
@nayakastha It looks like we'd have to run `dartfmt` then the [https://github.com/dart-lang/linter/pull/2557](https://github.com/dart-lang/linter/pull/2557) solution as part of our [pull-request.yml](https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/pull-request.yml) GitHub automation.

**Comment by nayakastha** [comment]
That would format the code but I am not sure it would add the missing trailing commas. Check here for reference [https://flutter.dev/docs/development/tools/formatting](https://flutter.dev/docs/development/tools/formatting)

**Comment by palisadoes** [comment]
So this issue would also require the use of the [flutter format command](https://flutter.dev/docs/development/tools/formatting#automatically-formatting-code-with-the-flutter-command), correct?

**Comment by nayakastha** [comment]
No sir, what flutter formatting does is - in case you have trailing commas, it will arrange it in a specific manner to make it look pretty but it doesn't manually add trailing commas in the code. Formatting works best if you already have a trailing comma while you write the code.

This is something that can be achieved by altering the configuration of the "Prettier" VSCode Extension. I am looking out for a way to do it through Github Actions.

**Comment by utkarshshendge** [comment]
Hi @palisadoes, I searched a few places to see if this is possible through Github Actions, but unfortunately, I was not able to find automation for this.
> This is something that can be achieved on an individual level by altering the configuration of the "Prettier" VSCode Extension. I am looking out for a way to do it through Github Actions.

@nayakastha It will be great if you succeed in finding automation for this. Else:

We will have to write a script that adds trailing commas and then runs the[ flutter format command](https://flutter.dev/docs/development/tools/formatting#automatically-formatting-code-with-the-flutter-command). This can be done with the help of a stack-based machine since we are mostly dealing with parentheses.
That is, after every suitable closing parentheses `  )` we add a `,`.  While this is easy, handling corner cases looks tough.
In order to deal with corner cases, we will have to do type checking so that the commas are not added in cases like this:
```
updateProgress(String message), {
  progressDialog.update(message: message);
}
```
Or while calling functions or, in the if-else statements, etc.

Also could you please tell me if PR #752 is on hold until this issue gets solved?

**Comment by nayakastha** [comment]
The only issue with the automation will be there are too many corner cases. And I am still searching for a way to remove all those and write a script.

**Comment by sumitra19jha** [comment]
@palisadoes We can work on writing a script where `))` is not accepted. If it is present then workflow can throw an error just like countline.py

**Comment by palisadoes** [comment]
@sumitra19jha please work with @nayakastha on creating a comprehensive solution. It's important to get this right. Create sub issues for the edge cases if necessary so that many people can work on it. When this is done, resubmit #786 in that context.
